#!/bin/bash

RESOLV_FILE="tst/resolv.conf"
DNS_LOCAL_STRING="nameserver 127.0.0.1"
FILE_START_COMMENT="# Generated by NetworkManager"


if test -e $RESOLV_FILE
  then
    RESOLV_FILE_NEW="$RESOLV_FILE.`date +%Y%m%d.%H%M%S`.back"
    echo "Found $RESOLV_FILE, backing up to: $RESOLV_FILE_NEW"
    cp -a $RESOLV_FILE $RESOLV_FILE_NEW
  else
    echo "File $RESOLV_FILE does not exist"
    exit 1
fi

exit $?
